#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
tmpfile="/tmp/easylog_tmp.json"

source ${DIR}/venv/bin/activate
python ${DIR}/easylog.py ${1} > ${tmpfile} && python ${DIR}/viewer.py ${tmpfile} | less -R     
deactivate

